### ISSUE TITLE
CT numberZigZags must be an integer

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#496]
```
circuit-construction-kit-dc : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: numberZigZags must be an integer: 11.9947
Error: Assertion failed: numberZigZags must be an integer: 11.9947
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/assert/js/assert.js:22:13)
    at Shape.zigZagToPoint (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/kite/js/Shape.js?bust=1557957750764:353:17)
    at new FuseNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/circuit-construction-kit-common/js/view/FuseNode.js?bust=1557957750764:63:10)
    at CircuitElementToolFactory.createFuseToolNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/circuit-construction-kit-common/js/view/CircuitElementToolFactory.js?bust=1557957750764:324:9)
    at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/circuit-construction-kit-dc/js/intro/view/IntroScreenView.js?bust=1557957750764:41:35)
    at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/circuit-construction-kit-dc/js/intro/IntroScreen.js?bust=1557957750764:64:18)
    at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/joist/js/Screen.js?bust=1557957750764:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/joist/js/Sim.js?bust=1557957750764:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/joist/js/Sim.js?bust=1557957750764:811:27
id: Bayes Chrome
Approximately 5/15/2019, 1:38:18 PM
circuit-construction-kit-dc : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: numberZigZags must be an integer: 11.9947
Error: Assertion failed: numberZigZags must be an integer: 11.9947
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/assert/js/assert.js:22:13)
    at Shape.zigZagToPoint (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/kite/js/Shape.js?bust=1557957750764:353:17)
    at new FuseNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/circuit-construction-kit-common/js/view/FuseNode.js?bust=1557957750764:63:10)
    at CircuitElementToolFactory.createFuseToolNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/circuit-construction-kit-common/js/view/CircuitElementToolFactory.js?bust=1557957750764:324:9)
    at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/circuit-construction-kit-dc/js/intro/view/IntroScreenView.js?bust=1557957750764:41:35)
    at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/circuit-construction-kit-dc/js/intro/IntroScreen.js?bust=1557957750764:64:18)
    at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/joist/js/Screen.js?bust=1557957750764:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/joist/js/Sim.js?bust=1557957750764:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557949098039/joist/js/Sim.js?bust=1557957750764:811:27
id: Bayes Chrome
Approximately 5/15/2019, 1:38:18 PM
```

**Comment by veillette** [comment]
I made a commit https://github.com/phetsims/circuit-construction-kit-common/commit/c2b62768e29ab4a9e91007628dede557c8deed9c that will resolve the issue since it forces the number of zig-zags to be an integer.

**Comment by veillette** [comment]
CT is now passing but the commit brings a visual change, that although hardly perceptible, should be review. Assigning to @Denz1994 since he is in the process of reviewing FuseNode (see https://github.com/phetsims/circuit-construction-kit-common/issues/495)

**Comment by Denz1994** [comment]
Thanks for handling this @veillette. The fuse node looks good and CT has been silent. Closing this issue.
