### ISSUE TITLE
CT Cannot read property disposeCircuitElement of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#569]
Occurs in multiple CCK sims
```
circuit-construction-kit-dc-virtual-lab : interactive-description-fuzzBoard : built : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'disposeCircuitElement' of null
TypeError: Cannot read property 'disposeCircuitElement' of null
    at Object.keydown (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:924:1188338)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:924:653256)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:924:653455)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:924:652997)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:924:648420)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:924:644805
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:924:598885)
    at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:924:645487)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:924:1632527)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzBoard&supportsDescriptions&memoryLimit=1000:924:1631437)
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
circuit-construction-kit-dc-virtual-lab : interactive-description-fuzzBoard : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'disposeCircuitElement' of null
TypeError: Cannot read property 'disposeCircuitElement' of null
    at Object.keydown (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/circuit-construction-kit-common/js/view/CircuitElementNode.js:64:21)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/scenery/js/input/Input.js:1818:25)
    at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/scenery/js/input/Input.js:1850:12)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/scenery/js/input/Input.js:1776:10)
    at Input.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/scenery/js/input/Input.js:1017:12)
    at Input.keydownAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/scenery/js/input/Input.js:681:14)
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/axon/js/Action.js:224:18)
    at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/scenery/js/input/Input.js:727:30)
    at KeyboardFuzzer.triggerDOMEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/scenery/js/accessibility/KeyboardFuzzer.js:221:37)
    at KeyboardFuzzer.triggerKeyDownUpEvents (https://bayes.colorado.edu/continuous-testing/snapshot-1584591344628/scenery/js/accessibility/KeyboardFuzzer.js:115:12)
id: Bayes Chrome
Approximately 3/18/2020, 10:15:44 PM
```

**Comment by samreid** [comment]
I pushed a proposed fix and will see what CT says.

**Comment by samreid** [comment]
CT is green for these shas, closing.
