### ISSUE TITLE
Report media task

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#579]
```
circuit-construction-kit-common : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Fatal error: Perennial task failed:
TypeError: Cannot read property 'includes' of undefined
at brands.forEach.brand (/data/share/phet/continuous-testing/ct-snapshots/1588849777407/chipper/js/grunt/Gruntfile.js:240:58)
at Array.forEach (<anonymous>:null:null)
at grunt.registerTask.wrapTask (/data/share/phet/continuous-testing/ct-snapshots/1588849777407/chipper/js/grunt/Gruntfile.js:240:16)
at Object.<anonymous> (/data/share/phet/continuous-testing/ct-snapshots/1588849777407/chipper/js/grunt/Gruntfile.js:106:13)
at Object.thisTask.fn (/data/share/phet/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/node_modules/grunt/lib/grunt/task.js:70:16)
at Object.<anonymous> (/data/share/phet/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/node_modules/grunt/lib/util/task.js:294:30)
at Task.runTaskFn (/data/share/phet/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/node_modules/grunt/lib/util/task.js:244:24)
at Task.<anonymous> (/data/share/phet/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/node_modules/grunt/lib/util/task.js:293:12)
at /data/share/phet/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/node_modules/grunt/lib/util/task.js:220:11
at process._tickCallback (internal/process/next_tick.js:61:11)

Full Error details:
{}
Snapshot from 5/7/2020, 5:09:37 AM
```

**Comment by samreid** [comment]
This is passing now in master, closing.
