### ISSUE TITLE
CT parent should not have child resistorNode

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#580]
In other CCK sims
```
circuit-construction-kit-dc : fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854684644%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: parent should not have child: resistorNode
Error: Assertion failed: parent should not have child: resistorNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/assert/js/assert.js:22:13)
at new Tandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:88:17)
at new GroupTandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:541:5)
at Tandem.createGroupTandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:305:12)
at new CircuitLayerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/js/view/CircuitLayerNode.js:310:96)
at new CCKCScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/js/view/CCKCScreenView.js:101:29)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/js/intro/view/IntroScreenView.js:51:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/js/intro/IntroScreen.js:61:16)
at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/joist/js/Screen.js:283:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/joist/js/Sim.js:808:16)
id: Bayes Chrome
Snapshot from 5/7/2020, 5:09:37 AM

----------------------------------

circuit-construction-kit-dc : interactive-description-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzz%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854069093%7D&brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: parent should not have child: resistorNode
Error: Assertion failed: parent should not have child: resistorNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/assert/js/assert.js:22:13)
at new Tandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:88:17)
at new GroupTandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:541:5)
at Tandem.createGroupTandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:305:12)
at new CircuitLayerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/js/view/CircuitLayerNode.js:310:96)
at new CCKCScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/js/view/CCKCScreenView.js:101:29)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/js/intro/view/IntroScreenView.js:51:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/js/intro/IntroScreen.js:61:16)
at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/joist/js/Screen.js:283:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/joist/js/Sim.js:808:16)
id: Bayes Chrome
Snapshot from 5/7/2020, 5:09:37 AM

----------------------------------

circuit-construction-kit-dc : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/build/phet/circuit-construction-kit-dc_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854284540%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'disposeCircuitElement' of null
TypeError: Cannot read property 'disposeCircuitElement' of null
at Object.keydown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/build/phet/circuit-construction-kit-dc_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854284540%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:920:1267908)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/build/phet/circuit-construction-kit-dc_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854284540%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:920:535023)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/build/phet/circuit-construction-kit-dc_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854284540%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:920:535222)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/build/phet/circuit-construction-kit-dc_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854284540%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:920:534764)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/build/phet/circuit-construction-kit-dc_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854284540%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:920:530196)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/build/phet/circuit-construction-kit-dc_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854284540%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:920:526583
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/build/phet/circuit-construction-kit-dc_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854284540%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:920:59557)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/build/phet/circuit-construction-kit-dc_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854284540%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:920:527269)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/build/phet/circuit-construction-kit-dc_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854284540%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:920:648349)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/build/phet/circuit-construction-kit-dc_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854284540%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:920:647259)
id: Bayes Chrome
Snapshot from 5/7/2020, 5:09:37 AM

----------------------------------

circuit-construction-kit-dc : interactive-description-fuzzBoard : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzzBoard%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588852739568%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: parent should not have child: resistorNode
Error: Assertion failed: parent should not have child: resistorNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/assert/js/assert.js:22:13)
at new Tandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:88:17)
at new GroupTandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:541:5)
at Tandem.createGroupTandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:305:12)
at new CircuitLayerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/js/view/CircuitLayerNode.js:310:96)
at new CCKCScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/js/view/CCKCScreenView.js:101:29)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/js/intro/view/IntroScreenView.js:51:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/js/intro/IntroScreen.js:61:16)
at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/joist/js/Screen.js:283:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/joist/js/Sim.js:808:16)
id: Bayes Chrome
Snapshot from 5/7/2020, 5:09:37 AM

----------------------------------

circuit-construction-kit-dc : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1588849777407%22%2C%22timestamp%22%3A1588854930552%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: parent should not have child: resistorNode
Error: Assertion failed: parent should not have child: resistorNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/assert/js/assert.js:22:13)
at new Tandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:88:17)
at new GroupTandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:541:5)
at Tandem.createGroupTandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/tandem/js/Tandem.js:305:12)
at new CircuitLayerNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/js/view/CircuitLayerNode.js:310:96)
at new CCKCScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-common/js/view/CCKCScreenView.js:101:29)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/js/intro/view/IntroScreenView.js:51:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/circuit-construction-kit-dc/js/intro/IntroScreen.js:61:16)
at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/joist/js/Screen.js:283:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588849777407/joist/js/Sim.js:808:16)
id: Bayes Chrome
Snapshot from 5/7/2020, 5:09:37 AM
```

**Comment by pixelzoom** [comment]
BAA has a similar problem (see https://github.com/phetsims/build-an-atom/issues/215), maybe they have something in common.

**Comment by samreid** [comment]
This has been clear on CT for a while, closing.
