### ISSUE TITLE
CT should not have listeners when a pointer is disposed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#582]
In the different cck sims:
```
circuit-construction-kit-dc : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592237323518/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1592237323518%22%2C%22timestamp%22%3A1592239124750%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Should not have listeners when a pointer is disposed
Error: Assertion failed: Should not have listeners when a pointer is disposed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592237323518/assert/js/assert.js:22:13)
at Touch.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592237323518/scenery/js/input/Pointer.js:378:15)
at Input.removePointer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592237323518/scenery/js/input/Input.js:972:13)
at Input.touchCancelAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592237323518/scenery/js/input/Input.js:444:14)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592237323518/axon/js/Action.js:225:18)
at Input.touchCancel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592237323518/scenery/js/input/Input.js:1249:28)
at InputFuzzer.touchCancel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592237323518/scenery/js/input/InputFuzzer.js:256:25)
at InputFuzzer.touchCancelAction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592237323518/scenery/js/input/InputFuzzer.js:63:10)
at InputFuzzer.fuzzEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592237323518/scenery/js/input/InputFuzzer.js:111:7)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1592237323518/joist/js/Sim.js:244:24
id: Bayes Chrome
Snapshot from 6/15/2020, 10:08:43 AM
```

**Comment by samreid** [comment]
This hasn't happened in several columns, let's reopen if it recurs.
