### ISSUE TITLE
CT Impossible set state from iterate unset state

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#594]
```
circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1598237187778%22%2C%22timestamp%22%3A1598238275830%7D
Uncaught Error: Assertion failed: Impossible set state from iterate; unset state:
{
"circuitConstructionKitDc.labScreen.model.circuit.circuitElements": {
"array": [
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_0",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_1",
"circuitConstructionKitDc.labScreen.model.circuit.wireGroup.wire_2",
"circuitConstructionKitDc.labScreen.model.circuit.batteryGroup.battery_1",
"circuitConstructionKitDc.labScreen.model.circuit.batteryGroup.battery_3"
]
},
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0": {
"startVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_0",
"endVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_1"
}
}
Error: Assertion failed: Impossible set state from iterate; unset state:
{
"circuitConstructionKitDc.labScreen.model.circuit.circuitElements": {
"array": [
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_0",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_1",
"circuitConstructionKitDc.labScreen.model.circuit.wireGroup.wire_2",
"circuitConstructionKitDc.labScreen.model.circuit.batteryGroup.battery_1",
"circuitConstructionKitDc.labScreen.model.circuit.batteryGroup.battery_3"
]
},
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0": {
"startVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_0",
"endVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_1"
}
}
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/assert/js/assert.js:22:13)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioStateEngine.js:350:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioStateEngine.js:252:31)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioStateEngine.js:271:10)
at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioEngineIO.js:230:43)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:276:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:163:36
at Array.map (<anonymous>)
at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:161:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:100:16
id: Bayes Chrome
Snapshot from 8/23/2020, 8:46:27 PM

----------------------------------

circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1598237187778%22%2C%22timestamp%22%3A1598249511536%7D
Uncaught Error: Assertion failed: countProperty should match array length.
Error: Assertion failed: countProperty should match array length.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/tandem/js/PhetioGroup.js:61:49
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/axon/js/TinyEmitter.js:71:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/axon/js/Property.js:277:25)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/axon/js/Property.js:327:47)
at PropertyStateHandler.attemptToApplyPhases (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/axon/js/PropertyStateHandler.js:311:41)
at PropertyStateHandler.undeferAndNotifyProperties (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/axon/js/PropertyStateHandler.js:224:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/axon/js/PropertyStateHandler.js:78:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/axon/js/Emitter.js:33:29
id: Bayes Chrome
Snapshot from 8/23/2020, 8:46:27 PM

----------------------------------

circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1598237187778%22%2C%22timestamp%22%3A1598261202182%7D
Uncaught Error: Assertion failed: Impossible set state from iterate; unset state:
{
"circuitConstructionKitDc.labScreen.model.circuit.circuitElements": {
"array": [
"circuitConstructionKitDc.labScreen.model.circuit.wireGroup.wire_0",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_2",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_4",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_5",
"circuitConstructionKitDc.labScreen.model.circuit.wireGroup.wire_1",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_6",
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~1"
]
},
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0": {
"startVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_12",
"endVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_13"
},
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~1": {
"startVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_22",
"endVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_23"
}
}
Error: Assertion failed: Impossible set state from iterate; unset state:
{
"circuitConstructionKitDc.labScreen.model.circuit.circuitElements": {
"array": [
"circuitConstructionKitDc.labScreen.model.circuit.wireGroup.wire_0",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_2",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_4",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_5",
"circuitConstructionKitDc.labScreen.model.circuit.wireGroup.wire_1",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_6",
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~1"
]
},
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0": {
"startVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_12",
"endVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_13"
},
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~1": {
"startVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_22",
"endVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_23"
}
}
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/assert/js/assert.js:22:13)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioStateEngine.js:350:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioStateEngine.js:252:31)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioStateEngine.js:271:10)
at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioEngineIO.js:230:43)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:276:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:163:36
at Array.map (<anonymous>)
at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:161:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:100:16
id: Bayes Chrome
Snapshot from 8/23/2020, 8:46:27 PM

----------------------------------

circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1598237187778%22%2C%22timestamp%22%3A1598272979468%7D
Uncaught Error: Assertion failed: Impossible set state from iterate; unset state:
{
"circuitConstructionKitDc.labScreen.model.circuit.circuitElements": {
"array": [
"circuitConstructionKitDc.labScreen.model.circuit.switchGroup.switch_0",
"circuitConstructionKitDc.labScreen.model.circuit.lightBulbGroup.lightBulb_0",
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0",
"circuitConstructionKitDc.labScreen.model.circuit.lightBulbGroup.lightBulb_1",
"circuitConstructionKitDc.labScreen.model.circuit.switchGroup.switch_3",
"circuitConstructionKitDc.labScreen.model.circuit.switchGroup.switch_4",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_3"
]
},
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0": {
"startVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_10",
"endVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_11"
}
}
Error: Assertion failed: Impossible set state from iterate; unset state:
{
"circuitConstructionKitDc.labScreen.model.circuit.circuitElements": {
"array": [
"circuitConstructionKitDc.labScreen.model.circuit.switchGroup.switch_0",
"circuitConstructionKitDc.labScreen.model.circuit.lightBulbGroup.lightBulb_0",
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0",
"circuitConstructionKitDc.labScreen.model.circuit.lightBulbGroup.lightBulb_1",
"circuitConstructionKitDc.labScreen.model.circuit.switchGroup.switch_3",
"circuitConstructionKitDc.labScreen.model.circuit.switchGroup.switch_4",
"circuitConstructionKitDc.labScreen.model.circuit.resistorGroup.resistor_3"
]
},
"circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0": {
"startVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_10",
"endVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_11"
}
}
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/assert/js/assert.js:22:13)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioStateEngine.js:350:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioStateEngine.js:252:31)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioStateEngine.js:271:10)
at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/PhetioEngineIO.js:230:43)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:276:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:163:36
at Array.map (<anonymous>)
at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:161:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io/js/phetioCommandProcessor.js:100:16
id: Bayes Chrome
Snapshot from 8/23/2020, 8:46:27 PM

----------------------------------

circuit-construction-kit-dc : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1598237187778%22%2C%22timestamp%22%3A1598238069692%7D
Uncaught Error: phetioElement not found: circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0
Error: phetioElement not found: circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0
at window.assert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/assert.js:32:13)
at Studio.onPhetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/js/studio.js:245:19)
at phetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/js/studio-main.js:44:10)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/Client.js:479:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/Client.js:348:26)
id: Bayes Chrome
Snapshot from 8/23/2020, 8:46:27 PM

----------------------------------

circuit-construction-kit-dc : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1598237187778%22%2C%22timestamp%22%3A1598249480557%7D
Uncaught Error: phetioElement not found: circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0
Error: phetioElement not found: circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0
at window.assert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/assert.js:32:13)
at Studio.onPhetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/js/studio.js:245:19)
at phetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/js/studio-main.js:44:10)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/Client.js:479:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/Client.js:348:26)
id: Bayes Chrome
Snapshot from 8/23/2020, 8:46:27 PM

----------------------------------

circuit-construction-kit-dc : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1598237187778%22%2C%22timestamp%22%3A1598262444561%7D
Uncaught Error: phetioElement not found: circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0
Error: phetioElement not found: circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0
at window.assert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/assert.js:32:13)
at Studio.onPhetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/js/studio.js:245:19)
at phetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/js/studio-main.js:44:10)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/Client.js:479:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/Client.js:348:26)
id: Bayes Chrome
Snapshot from 8/23/2020, 8:46:27 PM

----------------------------------

circuit-construction-kit-dc : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1598237187778%22%2C%22timestamp%22%3A1598273127705%7D
Uncaught Error: phetioElement not found: circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0
Error: phetioElement not found: circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeters~0
at window.assert (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/assert.js:32:13)
at Studio.onPhetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/js/studio.js:245:19)
at phetioElementAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/studio/js/studio-main.js:44:10)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/Client.js:479:56)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1598237187778/phet-io-wrappers/common/js/Client.js:348:26)
id: Bayes Chrome
Snapshot from 8/23/2020, 8:46:27 PM
```

**Comment by samreid** [comment]
This is on the agenda for Wednesday investigation.  On hold until then.

**Comment by zepumph** [comment]
High because it is breaking CT.

**Comment by zepumph** [comment]
Above I found that potentially one of the only things still using the old dynamic elements pattern is the seriesAmmeters. All other group tandems were actually unused. Perhaps this means you should convert this to use PhetioGroup, or maybe, like the other tools you can create them all at once. I don't know which is better.

I don't see a way to move forward keeping it with the old dynamic elements pattern since SeriesAmmeter is a subtype of CircuitElement, which supports PhetioGroup. I'd start there.

**Comment by zepumph** [comment]
I think this will be an easy fix, if this is all that CT was red about, I don't think it would be worth turning off state testing to support.

**Comment by samreid** [comment]
Thanks for identifying this was related to the series ammeters, I converted that in the commit.  Next error is:

```
Assertion failed: Impossible set state from iterate; unset state:
 {
  "circuitConstructionKitDc.labScreen.model.circuit.circuitElements": {
    "array": [
      "circuitConstructionKitDc.optionalTandem",
      "circuitConstructionKitDc.labScreen.model.circuit.highVoltageBatteryGroup.battery_3",
      "circuitConstructionKitDc.optionalTandem"
    ]
  },
  "circuitConstructionKitDc.labScreen.model.circuit.seriesAmmeterGroup.seriesAmmeter_0": {
    "startVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_8",
    "endVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_9"
  }
}
```

Perhaps something shouldn't be optional?

**Comment by samreid** [comment]
After fixing that, it fuzzes a bit longer and reports:

```
Assertion failed: Impossible set state from iterate; unset state:
 {
  "circuitConstructionKitDc.labScreen.model.circuit.highResistanceLightBulbGroup.highResistanceLightBulb_0": {
    "startVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_60",
    "endVertexID": "circuitConstructionKitDc.labScreen.model.circuit.vertexGroup.vertex_61"
  },
  "circuitConstructionKitDc.labScreen.model.circuit.highResistanceLightBulbGroup.highResistanceLightBulb_0.resistanceProperty": {
    "value": 1000,
    "numberType": "FloatingPoint",
    "range": {
      "min": 100,
      "max": 10000
    },
    "rangePhetioID": "circuitConstructionKitDc.labScreen.model.circuit.highResistanceLightBulbGroup.highResistanceLightBulb_0.resistanceProperty.rangeProperty"
  },
  "circuitConstructionKitDc.labScreen.model.circuit.highResistanceLightBulbGroup.highResistanceLightBulb_0.resistanceProperty.rangeProperty": {
    "value": {
      "min": 100,
      "max": 10000
    }
  }
}
```

**Comment by samreid** [comment]
It's fuzzing much longer after the commit.  CT will have the final word, closing until then.
