### ISSUE TITLE
CT cannot read property createNextElement of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#609]
Seen in a few cck sims.
```
circuit-construction-kit-dc : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603205225250%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read property 'createNextElement' of undefined
TypeError: Cannot read property 'createNextElement' of undefined
at createCircuitElementToolNode.iconScale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603205225250%7D&fuzz&memoryLimit=1000&phetioStandalone:864:1627253)
at VD.addInputListener.Tw.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603205225250%7D&fuzz&memoryLimit=1000&phetioStandalone:864:1514434)
at Object.down (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603205225250%7D&fuzz&memoryLimit=1000&phetioStandalone:864:1096657)
at Object.touchmove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603205225250%7D&fuzz&memoryLimit=1000&phetioStandalone:864:1096745)
at so.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603205225250%7D&fuzz&memoryLimit=1000&phetioStandalone:864:586024)
at so.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603205225250%7D&fuzz&memoryLimit=1000&phetioStandalone:864:586225)
at so.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603205225250%7D&fuzz&memoryLimit=1000&phetioStandalone:864:585815)
at so.branchChangeEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603205225250%7D&fuzz&memoryLimit=1000&phetioStandalone:864:585305)
at so.moveEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603205225250%7D&fuzz&memoryLimit=1000&phetioStandalone:864:584954)
at touchMoveAction.Ua.a.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603205225250%7D&fuzz&memoryLimit=1000&phetioStandalone:864:574747)
id: Bayes Chrome
Snapshot from 10/20/2020, 8:09:07 AM

----------------------------------

circuit-construction-kit-dc : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603204205772%7D&brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'createNextElement' of undefined
TypeError: Cannot read property 'createNextElement' of undefined
at createCircuitElementToolNode.iconScale (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/CircuitElementToolFactory.js:235:31)
at CircuitElementToolNode.addInputListener.DragListener.createForwardingListener.allowTouchSnag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/CircuitElementToolNode.js:67:30)
at Object.down (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/listeners/DragListener.js:811:11)
at Object.touchenter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/listeners/DragListener.js:815:40)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/input/Input.js:1816:33)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/input/Input.js:1857:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/input/Input.js:1783:10)
at Input.enterEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/input/Input.js:1718:14)
at Input.branchChangeEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/input/Input.js:1688:12)
at Input.downEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/input/Input.js:1595:29)
id: Bayes Chrome
Snapshot from 10/20/2020, 8:09:07 AM

----------------------------------

circuit-construction-kit-dc : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603203753271%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitElementToolbox.carousel.tools.lightBulbToolNode.lightBulbIcon
Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitElementToolbox.carousel.tools.lightBulbToolNode.lightBulbIcon
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/assert/js/assert.js:22:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io/js/phetioEngine.js:420:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io/js/phetioEngine.js:1035:49)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/tandem/js/Tandem.js:166:38)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/tandem/js/PhetioObject.js:311:17)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:5382:51)
at CCKCLightBulbNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:5354:10)
at new Node (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:581:10)
at new CircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/CircuitElementNode.js:40:5)
at new FixedCircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/FixedCircuitElementNode.js:58:5)
id: Bayes Chrome
Snapshot from 10/20/2020, 8:09:07 AM

----------------------------------

circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603204209256%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitElementToolbox.carousel.tools.lightBulbToolNode.lightBulbIcon
Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitElementToolbox.carousel.tools.lightBulbToolNode.lightBulbIcon
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/assert/js/assert.js:22:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io/js/phetioEngine.js:420:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io/js/phetioEngine.js:1035:49)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/tandem/js/Tandem.js:166:38)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/tandem/js/PhetioObject.js:311:17)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:5382:51)
at CCKCLightBulbNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:5354:10)
at new Node (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:581:10)
at new CircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/CircuitElementNode.js:40:5)
at new FixedCircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/FixedCircuitElementNode.js:58:5)
id: Bayes Chrome
Snapshot from 10/20/2020, 8:09:07 AM

----------------------------------

circuit-construction-kit-dc : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/studio/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1603202947269%22%2C%22timestamp%22%3A1603204045764%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitElementToolbox.carousel.tools.lightBulbToolNode.lightBulbIcon
Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitElementToolbox.carousel.tools.lightBulbToolNode.lightBulbIcon
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/assert/js/assert.js:22:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io/js/phetioEngine.js:420:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io/js/phetioEngine.js:1035:49)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/tandem/js/Tandem.js:166:38)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/tandem/js/PhetioObject.js:311:17)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:5382:51)
at CCKCLightBulbNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:5354:10)
at new Node (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:581:10)
at new CircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/CircuitElementNode.js:40:5)
at new FixedCircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/FixedCircuitElementNode.js:58:5)
id: Bayes Chrome
Snapshot from 10/20/2020, 8:09:07 AM

----------------------------------

circuit-construction-kit-dc : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io-wrappers/phet-io-wrappers-tests.html?sim=circuit-construction-kit-dc&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: circuit-construction-kit-dc: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitElementToolbox.carousel.tools.lightBulbToolNode.lightBulbIcon
Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitElementToolbox.carousel.tools.lightBulbToolNode.lightBulbIcon
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/assert/js/assert.js:22:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io/js/phetioEngine.js:420:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io/js/phetioEngine.js:1035:49)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/tandem/js/Tandem.js:166:38)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/tandem/js/PhetioObject.js:311:17)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:5382:51)
at CCKCLightBulbNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:5354:10)
at new Node (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:581:10)
at new CircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/CircuitElementNode.js:40:5)
at new FixedCircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/FixedCircuitElementNode.js:58:5)

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 10/20/2020, 8:09:07 AM

----------------------------------

circuit-construction-kit-dc : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io-wrappers/phet-io-wrappers-tests.html?sim=circuit-construction-kit-dc
3 out of 4 tests passed. 1 failed.
SimTests: circuit-construction-kit-dc: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitElementToolbox.carousel.tools.lightBulbToolNode.lightBulbIcon
Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitElementToolbox.carousel.tools.lightBulbToolNode.lightBulbIcon
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/assert/js/assert.js:22:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io/js/phetioEngine.js:420:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/phet-io/js/phetioEngine.js:1035:49)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/tandem/js/Tandem.js:166:38)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/tandem/js/PhetioObject.js:311:17)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:5382:51)
at CCKCLightBulbNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:5354:10)
at new Node (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/scenery/js/nodes/Node.js:581:10)
at new CircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/CircuitElementNode.js:40:5)
at new FixedCircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603202947269/circuit-construction-kit-common/js/view/FixedCircuitElementNode.js:58:5)

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 10/20/2020, 8:09:07 AM
```

**Comment by samreid** [comment]
Thanks @KatieWoe.  I pushed a fix that corrects it on my side, closing for now.
