### ISSUE TITLE
CT right-hand-side-value must be a number OR CT mnaVoltageDrop out of range

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#694]
```
circuit-construction-kit-ac : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1618459372043%22%2C%22timestamp%22%3A1618464602377%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: the right-hand-side-value must be a number
Error: Assertion failed: the right-hand-side-value must be a number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/assert/js/assert.js:25:13)
at ModifiedNodalAnalysisCircuit.solve (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:352:17)
at DynamicCircuit.solvePropagate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/DynamicCircuit.js:150:36)
at DynamicState.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/DynamicCircuit.js:398:41)
at Object.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/DynamicCircuit.js:162:30)
at TimestepSubdivisions.errorAcceptable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:83:26)
at TimestepSubdivisions.getTimestep (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:65:20)
at TimestepSubdivisions.stepInTimeWithHistory (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:41:32)
at DynamicCircuit.solveWithSubdivisions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/DynamicCircuit.js:167:36)
at Function.solveModifiedNodalAnalysis (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618459372043/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:179:40)
id: Bayes Chrome
Snapshot from 4/14/2021, 10:02:52 PM
```

**Comment by samreid** [comment]
I added an earlier error that may help.

**Comment by samreid** [comment]
I noticed that lately this problem is only showing up in ac-virtual-lab.  I fuzzed for 5+ minutes on my local and could not see the problem.  So I added a `toString` function (unbuilt mode only) to show what circuit elements are in the circuit.  Maybe it will help us identify what components are contributing to the problem.  (Or maybe we will just see that every kind of circuit element appears because fuzzing creates everything).

**Comment by samreid** [comment]
I caught this problem while working on #704 and noticed the capacitor currents and voltages are on the high side:

![image](https://user-images.githubusercontent.com/679486/124031435-898d1f80-d9b4-11eb-82b5-352145aa419d.png)

Same with the inductors:

![image](https://user-images.githubusercontent.com/679486/124031518-a6c1ee00-d9b4-11eb-8132-e483e49b4b37.png)

**Comment by samreid** [comment]
I added some more upstream assertions, but I'm not sure how it will help resolve the problem.

**Comment by samreid** [comment]
@kathy-phet says it would be nice if this would pass CT.  Even if we don't fully understand and solve, we should make sure CT is running clear.  @kathy-phet recommended we could reset the dynamics if the values get too high, and see if there are other fuzzing issues?  We don't want the sim to crash, and we don't want to see issues on CT.

@kathy-phet said @jonathanolson could provide support for 2 hours or so, to see if we can track it down.

**Comment by samreid** [comment]
There is a chance this is related to https://github.com/phetsims/circuit-construction-kit-common/issues/693#issuecomment-898694052, let's get that working before investigating this.

**Comment by samreid** [comment]
The proposal in the commit is to clamp values to a threshold of 1E20 (signed).  I'll let CT test that for a few rounds.

**Comment by samreid** [comment]
We are still seeing NaN from today's CT:

```
circuit-construction-kit-ac : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631173379982/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631173379982%22%2C%22timestamp%22%3A1631188098853%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: the right-hand-side-value must be a number. Instead it was NaN.
Error: Assertion failed: the right-hand-side-value must be a number. Instead it was NaN.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631173379982/assert/js/assert.js:25:13)
at ModifiedNodalAnalysisCircuit.solve (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631173379982/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:394:17)
at DynamicCircuit.solvePropagate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631173379982/circuit-construction-kit-common/js/model/DynamicCircuit.js:162:36)
at DynamicState.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631173379982/circuit-construction-kit-common/js/model/DynamicCircuit.js:437:41)
at Object.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631173379982/circuit-construction-kit-common/js/model/DynamicCircuit.js:175:30)
at TimestepSubdivisions.search (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631173379982/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:79:28)
at TimestepSubdivisions.stepInTimeWithHistory (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631173379982/circuit-construction-kit-common/js/model/TimestepSubdivisions.js:43:27)
at DynamicCircuit.solveWithSubdivisions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631173379982/circuit-construction-kit-common/js/model/DynamicCircuit.js:180:36)
at Function.solveModifiedNodalAnalysis (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631173379982/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:206:40)
at Circuit.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631173379982/circuit-construction-kit-common/js/model/Circuit.js:911:36)
id: Bayes Chrome
Snapshot from 9/9/2021, 1:42:59 AM
```

**Comment by samreid** [comment]
I added another layer of diagnostic information for when this recurs.

**Comment by samreid** [comment]
Nothing from the last several columns, on hold and I'll check again later.

**Comment by samreid** [comment]
I haven't seen this in many columns, closing again until it recurs.
