### ISSUE TITLE
CT pageNumber out of range

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#698]
```
circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620272831901%22%2C%22timestamp%22%3A1620288859175%7D
Uncaught Error: Uncaught Error: Assertion failed: pageNumber out of range: 4
Error: Assertion failed: pageNumber out of range: 4
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/assert/js/assert.js:25:13)
at pageNumberListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/sun/js/Carousel.js:270:17)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:269:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:184:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/sun/js/Carousel.js:327:54
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Emitter.js:64:19)
id: Bayes Chrome
Snapshot from 5/5/2021, 9:47:11 PM
```

**Comment by samreid** [comment]
I remember when this was happening, but I haven't seen it on CT for a while.  Closing until we see it again.

**Comment by samreid** [comment]
This recurred on CT again.

**Comment by samreid** [comment]
I was able to reproduce the problem by running CCK DC in the state wrapper, then choosing next page in the upstream wrapper, then choosing previous page in the downstream wrapper. The commit adds instrumentation to the page number property, and seems to address the problem. The naming and instrumentation seem straightforward, so I don't think this warrants review at this time, but I will give @arouinfar a heads-up to take a look once we design a phet-io sim with Carousel.
