### ISSUE TITLE
CT mnaVoltageDrop out of range

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#711]
```
circuit-construction-kit-ac : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626390005602/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1626390005602%22%2C%22timestamp%22%3A1626422404674%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: mnaVoltageDrop out of range
Error: Assertion failed: mnaVoltageDrop out of range
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626390005602/assert/js/assert.js:25:13)
at InductorAdapter.applySolution (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626390005602/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:142:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626390005602/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:247:66
at Array.forEach (<anonymous>)
at Function.solveModifiedNodalAnalysis (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626390005602/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:247:22)
at Circuit.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626390005602/circuit-construction-kit-common/js/model/Circuit.js:912:36)
at CircuitConstructionKitModel.stepOnce (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626390005602/circuit-construction-kit-common/js/model/CircuitConstructionKitModel.js:218:64)
at CircuitConstructionKitModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626390005602/circuit-construction-kit-common/js/model/CircuitConstructionKitModel.js:244:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626390005602/joist/js/Sim.js:307:22
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626390005602/axon/js/Action.js:227:18)
id: Bayes Chrome
Snapshot from 7/15/2021, 5:00:05 PM
```

**Comment by samreid** [comment]
This is an upstream error for #694.

**Comment by samreid** [comment]
Let's track it in https://github.com/phetsims/circuit-construction-kit-common/issues/694, closing.
