### ISSUE TITLE
CT decimal is not defined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#716]
Happens in a number of cck sims
```
circuit-construction-kit-dc-virtual-lab : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629186268121%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught ReferenceError: Decimal is not defined
ReferenceError: Decimal is not defined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629186268121%7D&fuzz&memoryLimit=1000:882:996970
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629186268121%7D&fuzz&memoryLimit=1000:882:1843184
at Object.phet.chipper.runWebpack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629186268121%7D&fuzz&memoryLimit=1000:882:1843188)
at i (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629186268121%7D&fuzz&memoryLimit=1000:883:1040)
at t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629186268121%7D&fuzz&memoryLimit=1000:883:1068)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629186268121%7D&fuzz&memoryLimit=1000:883:1093
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629186268121%7D&fuzz&memoryLimit=1000:883:1195
id: Bayes Chrome
Snapshot from 8/17/2021, 12:58:05 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629186680703%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught ReferenceError: Decimal is not defined
ReferenceError: Decimal is not defined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:21:19
id: Bayes Chrome
Snapshot from 8/17/2021, 12:58:05 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : interactive-description-fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629188407123%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught ReferenceError: Decimal is not defined
ReferenceError: Decimal is not defined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629188407123%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:996970
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629188407123%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:1843184
at Object.phet.chipper.runWebpack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629188407123%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:1843188)
at i (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629188407123%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:883:1040)
at t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629188407123%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:883:1068)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629188407123%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:883:1093
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629188407123%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:883:1195
id: Bayes Chrome
Snapshot from 8/17/2021, 12:58:05 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629188103043%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught ReferenceError: Decimal is not defined
ReferenceError: Decimal is not defined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:21:19
id: Bayes Chrome
Snapshot from 8/17/2021, 12:58:05 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629185909360%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught ReferenceError: Decimal is not defined
ReferenceError: Decimal is not defined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629185909360%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:996970
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629185909360%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1843184
at Object.phet.chipper.runWebpack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629185909360%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:882:1843188)
at i (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629185909360%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:883:1040)
at t (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629185909360%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:883:1068)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629185909360%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:883:1093
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/build/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629185909360%7D&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000:883:1195
id: Bayes Chrome
Snapshot from 8/17/2021, 12:58:05 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629187324054%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught ReferenceError: Decimal is not defined
ReferenceError: Decimal is not defined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:21:19
id: Bayes Chrome
Snapshot from 8/17/2021, 12:58:05 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629186425789%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught ReferenceError: Decimal is not defined
ReferenceError: Decimal is not defined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:21:19
id: Bayes Chrome
Snapshot from 8/17/2021, 12:58:05 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629184947463%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught ReferenceError: Decimal is not defined
ReferenceError: Decimal is not defined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:21:19
id: Bayes Chrome
Snapshot from 8/17/2021, 12:58:05 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1629183485173%22%2C%22timestamp%22%3A1629189594309%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught ReferenceError: Decimal is not defined
ReferenceError: Decimal is not defined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629183485173/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisCircuit.js:21:19
id: Bayes Chrome
Snapshot from 8/17/2021, 12:58:05 AM
```

**Comment by samreid** [comment]
Thanks @KatieWoe, I pushed a proposed fix.

**Comment by KatieWoe** [comment]
This still seems to be seen in CT

**Comment by samreid** [comment]
Thanks, I added a `grunt update` step.
