### ISSUE TITLE
non-ohmic value gets out-of-range resistance

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#723]
from CT

```
circuit-construction-kit-dc-virtual-lab : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630081608521/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1630081608521%22%2C%22timestamp%22%3A1630082726523%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: value failed isValidValue: 1.1175791282059751e+21
Error: Assertion failed: value failed isValidValue: 1.1175791282059751e+21
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630081608521/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630081608521/axon/js/ValidatorDef.js:324:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630081608521/axon/js/validate.js:36:18)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630081608521/axon/js/NumberProperty.js:105:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630081608521/axon/js/NumberProperty.js:138:12
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630081608521/axon/js/TinyEmitter.js:86:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630081608521/axon/js/Property.js:271:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630081608521/axon/js/Property.js:186:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630081608521/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630081608521/circuit-construction-kit-common/js/model/ModifiedNodalAnalysisAdapter.js:236:65
id: Bayes Chrome
Snapshot from 8/27/2021, 10:26:48 AM
```

Discovered while checking CT for https://github.com/phetsims/circuit-construction-kit-common/issues/694

**Comment by samreid** [comment]
This CT error disappears right after this commit, nice!  Closing.
