### ISSUE TITLE
CT Build failed with status code 1

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#729]
```
circuit-construction-kit-dc : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (circuit-construction-kit-dc, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 6734ms
>> Production minification complete: 36733ms (2154403 bytes)
>> Debug minification complete: 0ms (7127437 bytes)
Building brand: phet-io
>> Webpack build complete: 4366ms
>> Production minification complete: 35361ms (2181234 bytes)
>> Debug minification complete: 35628ms (2479294 bytes)
>> No client guides found at ../phet-io-client-guides/circuit-construction-kit-dc/, no guides being built.
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1630344483726/chipper/js/grunt/copySupplementalPhetioFiles.js:316:5)
at async module.exports (/data/share/phet/continuous-testing/ct-snapshots/1630344483726/chipper/js/grunt/buildRunnable.js:355:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1630344483726/chipper/js/grunt/Gruntfile.js:252:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1630344483726/chipper/js/grunt/Gruntfile.js:70:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error in fulfilling chunk Promise: Error: Timeout in generatePhetioMacroAPI
at Timeout._onTimeout (/data/share/phet/continuous-testing/ct-snapshots/1630344483726/chipper/js/phet-io/generatePhetioMacroAPI.js:94:35)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
Snapshot from 8/30/2021, 11:28:03 AM
```

**Comment by samreid** [comment]
This appears to be a spurious occurrence of https://github.com/phetsims/chipper/issues/1022.  I did not see the problem in a local build.  Unassigning from milestone.

**Comment by zepumph** [comment]
Work has been done such that https://github.com/phetsims/chipper/issues/1022 is fixed for me. Closing
