### ISSUE TITLE
CT pageNumber out of range

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#743]
Seems to be in CCK DC
```
circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632508894542/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1632508894542%22%2C%22timestamp%22%3A1632514826987%7D
Uncaught Error: Uncaught Error: Assertion failed: pageNumber out of range: 3
Error: Assertion failed: pageNumber out of range: 3
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632508894542/assert/js/assert.js:25:13)
at pageNumberListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632508894542/sun/js/Carousel.js:270:17)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632508894542/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632508894542/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632508894542/axon/js/Property.js:186:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632508894542/sun/js/Carousel.js:327:54
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632508894542/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632508894542/axon/js/Emitter.js:39:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632508894542/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1632508894542/axon/js/Emitter.js:64:19)
id: Bayes Chrome
Snapshot from 9/24/2021, 12:41:34 PM
```

**Comment by samreid** [comment]
Thanks, let's track it in https://github.com/phetsims/circuit-construction-kit-common/issues/698 where it was first reported.
