### ISSUE TITLE
CT Should be empty before adding everything

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#747]
```
circuit-construction-kit-ac : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634011942782/phet-io-wrappers/state/?sim=circuit-construction-kit-ac&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634011942782%22%2C%22timestamp%22%3A1634015951033%7D
Uncaught Error: Uncaught Error: Assertion failed: Should be empty before adding everything
Error: Assertion failed: Should be empty before adding everything
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634011942782/assert/js/assert.js:25:13)
at PDOMDisplaysInfo.addAllPDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634011942782/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:201:15)
at PDOMDisplaysInfo.onVisibilityChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634011942782/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:116:14)
at CurrentChartNode.onVisiblePropertyChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634011942782/scenery/js/nodes/Node.js:3754:28)
at TinyForwardingProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634011942782/axon/js/TinyEmitter.js:68:48)
at TinyForwardingProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634011942782/axon/js/TinyForwardingProperty.js:181:10)
at TinyForwardingProperty.onTargetPropertyChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634011942782/axon/js/TinyForwardingProperty.js:128:10)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634011942782/axon/js/TinyEmitter.js:86:9)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634011942782/axon/js/Property.js:275:23)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634011942782/axon/js/Property.js:325:47)
id: Bayes Chrome
Snapshot from 10/11/2021, 10:12:22 PM
```

**Comment by samreid** [comment]
This is being called from `PDOMDisplaysInfo`, @zepumph or @jessegreenberg can you please advise?

**Comment by jessegreenberg** [comment]
I was able to hit this quickly by fuzzing the state circuit-construction-kit-ac in the state wrapper. The Node for PDOMDisplaysInfo is a StopwatchNode.
![image](https://user-images.githubusercontent.com/6396244/136997521-57666635-f2db-4eae-8479-6547eed78371.png)

**Comment by zepumph** [comment]
>I was able to hit this quickly by fuzzing circuit-construction-kit-ac in the state wrapper. The Node for PDOMDisplaysInfo is a StopwatchNode.

But is it always that? Over in https://github.com/phetsims/greenhouse-effect/issues/46 we found that it could be many Nodes, it seems like it is something about dependency order when setting state in the PhET-iO state engine that I don't quite understand.

**Comment by jessegreenberg** [comment]
No, sorry - I didn't mean to suggest it was always that. It does seem more general.

**Comment by jessegreenberg** [comment]
This one was fixed by https://github.com/phetsims/scenery/issues/1312, closing.
