### ISSUE TITLE
CT cannot read properties of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#750]
```
circuit-construction-kit-black-box-study : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291981803%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'TEST')
TypeError: Cannot read properties of undefined (reading 'TEST')
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291981803%7D&fuzz&memoryLimit=1000:979:1229034
at ht.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291981803%7D&fuzz&memoryLimit=1000:979:81260)
at new pD (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291981803%7D&fuzz&memoryLimit=1000:979:1229018)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291981803%7D&fuzz&memoryLimit=1000:979:1771010
at Qt.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291981803%7D&fuzz&memoryLimit=1000:979:81260)
at new _G (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291981803%7D&fuzz&memoryLimit=1000:979:1770927)
at tH.name [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291981803%7D&fuzz&memoryLimit=1000:979:1772238)
at tH.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291981803%7D&fuzz&memoryLimit=1000:979:853444)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291981803%7D&fuzz&memoryLimit=1000:979:1149255)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291981803%7D&fuzz&memoryLimit=1000:979:1149408
id: Bayes Chrome
Snapshot from 10/15/2021, 3:08:24 AM

----------------------------------

circuit-construction-kit-black-box-study : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634293107930%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'TEST')
TypeError: Cannot read properties of undefined (reading 'TEST')
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:149:42
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/axon/js/Property.js:326:9)
at new BlackBoxSceneModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:147:27)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxScreenView.js:32:97
at StringProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/axon/js/Property.js:326:9)
at new BlackBoxScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxScreenView.js:24:43)
at BlackBoxScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/BlackBoxScreen.js:40:79)
at BlackBoxScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Screen.js:205:27)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Sim.js:617:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Sim.js:624:29
id: Bayes Chrome
Snapshot from 10/15/2021, 3:08:24 AM

----------------------------------

circuit-construction-kit-black-box-study : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291102423%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'TEST')
TypeError: Cannot read properties of undefined (reading 'TEST')
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:149:42
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/axon/js/Property.js:326:9)
at new BlackBoxSceneModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:147:27)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxScreenView.js:32:97
at StringProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/axon/js/Property.js:326:9)
at new BlackBoxScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxScreenView.js:24:43)
at BlackBoxScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/BlackBoxScreen.js:40:79)
at BlackBoxScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Screen.js:205:27)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Sim.js:617:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Sim.js:624:29
id: Bayes Chrome
Snapshot from 10/15/2021, 3:08:24 AM

----------------------------------

circuit-construction-kit-black-box-study : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634294521543%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'TEST')
TypeError: Cannot read properties of undefined (reading 'TEST')
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:149:42
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/axon/js/Property.js:326:9)
at new BlackBoxSceneModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:147:27)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxScreenView.js:32:97
at StringProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/axon/js/Property.js:326:9)
at new BlackBoxScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxScreenView.js:24:43)
at BlackBoxScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-black-box-study/js/blackbox/BlackBoxScreen.js:40:79)
at BlackBoxScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Screen.js:205:27)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Sim.js:617:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Sim.js:624:29
id: Bayes Chrome
Snapshot from 10/15/2021, 3:08:24 AM
```
and
```
circuit-construction-kit-dc : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291219442%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read properties of undefined (reading 'typeName')
TypeError: Cannot read properties of undefined (reading 'typeName')
at h (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291219442%7D&fuzz&memoryLimit=1000&phetioStandalone:885:198298)
at Object.getData (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291219442%7D&fuzz&memoryLimit=1000&phetioStandalone:885:6702)
at E.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291219442%7D&fuzz&memoryLimit=1000&phetioStandalone:885:181574)
at E._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291219442%7D&fuzz&memoryLimit=1000&phetioStandalone:885:6587)
at E.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291219442%7D&fuzz&memoryLimit=1000&phetioStandalone:885:6201)
at m (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291219442%7D&fuzz&memoryLimit=1000&phetioStandalone:885:802996)
at s.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291219442%7D&fuzz&memoryLimit=1000&phetioStandalone:885:11907)
at e.phetioOuterType (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291219442%7D&fuzz&memoryLimit=1000&phetioStandalone:885:2758)
at d.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291219442%7D&fuzz&memoryLimit=1000&phetioStandalone:885:1770)
at d.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/circuit-construction-kit-dc/build/phet-io/circuit-construction-kit-dc_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634291219442%7D&fuzz&memoryLimit=1000&phetioStandalone:885:2924)
id: Bayes Chrome
Snapshot from 10/15/2021, 3:08:24 AM

----------------------------------

circuit-construction-kit-dc : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/studio/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634288904240%22%2C%22timestamp%22%3A1634292085996%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioType passed to Property must be specified. Tandem.phetioID: circuitConstructionKitDc.introScreen.model.circuit.currentTypeProperty
Error: Assertion failed: phetioType passed to Property must be specified. Tandem.phetioID: circuitConstructionKitDc.introScreen.model.circuit.currentTypeProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/assert/js/assert.js:25:13)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/axon/js/Property.js:75:23)
at new Circuit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-common/js/model/Circuit.js:81:36)
at new CircuitConstructionKitModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-common/js/model/CircuitConstructionKitModel.js:49:24)
at new IntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-dc/js/intro/model/IntroModel.js:15:9)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/circuit-construction-kit-dc/js/intro/IntroScreen.js:56:21)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Screen.js:193:28)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Sim.js:614:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634288904240/chipper/dist/joist/js/Sim.js:624:29
id: Bayes Chrome
Snapshot from 10/15/2021, 3:08:24 AM
```

**Comment by samreid** [comment]
I pushed a fix that corrects the problem locally.  Closing until next time!
