### ISSUE TITLE
CT there should be at least as many PDOMDisplays as Displays

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#760]
```
circuit-construction-kit-ac : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/phet-io-wrappers/state/?sim=circuit-construction-kit-ac&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634648928056%22%2C%22timestamp%22%3A1634651021539%7D
Uncaught Error: Uncaught Error: Assertion failed: there should be at least as many PDOMDisplays as Displays
Error: Assertion failed: there should be at least as many PDOMDisplays as Displays
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/assert/js/assert.js:25:13)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/chipper/dist/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:235:19)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/chipper/dist/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:251:45)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/chipper/dist/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:251:45)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/chipper/dist/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:251:45)
at PDOMDisplaysInfo.removeAllPDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/chipper/dist/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:197:14)
at PDOMDisplaysInfo.onVisibilityChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/chipper/dist/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:101:22)
at LabScreenView.onVisiblePropertyChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/chipper/dist/scenery/js/nodes/Node.js:3292:32)
at TinyForwardingProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/chipper/dist/axon/js/TinyEmitter.js:51:52)
at TinyForwardingProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634648928056/chipper/dist/axon/js/TinyForwardingProperty.js:150:14)
id: Bayes Chrome
Snapshot from 10/19/2021, 7:08:48 AM
```

**Comment by samreid** [comment]
I added the sims to phet-io-state-unsupported for now, self-unassigning until there is progress in https://github.com/phetsims/scenery/issues/1312

**Comment by zepumph** [comment]
A fix has been pushed over in [phetsims/scenery#1312 (comment)](https://github.com/phetsims/scenery/issues/1312#issuecomment-1047142324), next steps for this issue are to make sure it is being tested on CT in the state wrapper. This will ensure we got the fix correct.

**Comment by samreid** [comment]
OK I added it back to the state tests.

**Comment by zepumph** [comment]
Yay!
