### ISSUE TITLE
CT should be a fixed length circuit element

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#767]
```
circuit-construction-kit-black-box-study : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1635144588043%22%2C%22timestamp%22%3A1635148988633%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should be a fixed length circuit element
Error: Assertion failed: should be a fixed length circuit element
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/assert/js/assert.js:25:13)
at CircuitLayerNode.rotateAboutFixedPivot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/CircuitLayerNode.js:463:23)
at CircuitLayerNode.dragVertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/CircuitLayerNode.js:506:30)
at CircuitLayerNodeDragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/VertexNode.js:139:34)
at CircuitLayerNodeDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/PressListener.js:392:14)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/DragListener.js:212:42)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/axon/js/Action.js:171:22)
at CircuitLayerNodeDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/DragListener.js:338:26)
at CircuitLayerNodeDragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/PressListener.js:703:22)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/input/Input.js:1731:31)
id: Bayes Chrome
Snapshot from 10/25/2021, 12:49:48 AM

----------------------------------

circuit-construction-kit-black-box-study : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1635144588043%22%2C%22timestamp%22%3A1635152891926%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should be a fixed length circuit element
Error: Assertion failed: should be a fixed length circuit element
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/assert/js/assert.js:25:13)
at CircuitLayerNode.rotateAboutFixedPivot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/CircuitLayerNode.js:463:23)
at CircuitLayerNode.dragVertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/CircuitLayerNode.js:506:30)
at CircuitLayerNodeDragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/VertexNode.js:139:34)
at CircuitLayerNodeDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/PressListener.js:392:14)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/DragListener.js:212:42)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/axon/js/Action.js:171:22)
at CircuitLayerNodeDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/DragListener.js:338:26)
at CircuitLayerNodeDragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/PressListener.js:703:22)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/input/Input.js:1731:31)
id: Bayes Chrome
Snapshot from 10/25/2021, 12:49:48 AM

----------------------------------

circuit-construction-kit-black-box-study : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1635144588043%22%2C%22timestamp%22%3A1635162343869%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: should be a fixed length circuit element
Error: Assertion failed: should be a fixed length circuit element
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/assert/js/assert.js:25:13)
at CircuitLayerNode.rotateAboutFixedPivot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/CircuitLayerNode.js:463:23)
at CircuitLayerNode.dragVertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/CircuitLayerNode.js:506:30)
at CircuitLayerNodeDragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/VertexNode.js:139:34)
at CircuitLayerNodeDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/PressListener.js:392:14)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/DragListener.js:212:42)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/axon/js/Action.js:171:22)
at CircuitLayerNodeDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/DragListener.js:338:26)
at CircuitLayerNodeDragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/PressListener.js:703:22)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/input/Input.js:1731:31)
id: Bayes Chrome
Snapshot from 10/25/2021, 12:49:48 AM

----------------------------------

circuit-construction-kit-black-box-study : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1635144588043%22%2C%22timestamp%22%3A1635146788423%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should be a fixed length circuit element
Error: Assertion failed: should be a fixed length circuit element
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/assert/js/assert.js:25:13)
at CircuitLayerNode.rotateAboutFixedPivot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/CircuitLayerNode.js:463:23)
at CircuitLayerNode.dragVertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/CircuitLayerNode.js:506:30)
at CircuitLayerNodeDragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/VertexNode.js:139:34)
at CircuitLayerNodeDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/PressListener.js:392:14)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/DragListener.js:212:42)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/axon/js/Action.js:171:22)
at CircuitLayerNodeDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/DragListener.js:338:26)
at CircuitLayerNodeDragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/PressListener.js:703:22)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/input/Input.js:1731:31)
id: Bayes Chrome
Snapshot from 10/25/2021, 12:49:48 AM

----------------------------------

circuit-construction-kit-black-box-study : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1635144588043%22%2C%22timestamp%22%3A1635163243583%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should be a fixed length circuit element
Error: Assertion failed: should be a fixed length circuit element
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/assert/js/assert.js:25:13)
at CircuitLayerNode.rotateAboutFixedPivot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/CircuitLayerNode.js:463:23)
at CircuitLayerNode.dragVertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/CircuitLayerNode.js:506:30)
at CircuitLayerNodeDragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/circuit-construction-kit-common/js/view/VertexNode.js:139:34)
at CircuitLayerNodeDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/PressListener.js:392:14)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/DragListener.js:212:42)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/axon/js/Action.js:171:22)
at CircuitLayerNodeDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/DragListener.js:338:26)
at CircuitLayerNodeDragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/listeners/PressListener.js:703:22)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635144588043/chipper/dist/scenery/js/input/Input.js:1731:31)
id: Bayes Chrome
Snapshot from 10/25/2021, 12:49:48 AM
```

**Comment by samreid** [comment]
Even though we originally wanted to maintain black-box-study alongside CCK AC development, it has been too complex and time consuming.  For now, I've removed that screen from main.
