### ISSUE TITLE
CT all descendants must be disposed by the next frame

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#842]
```
circuit-construction-kit-ac : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643937517178%22%2C%22timestamp%22%3A1643941191052%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.rlcScreen.model.circuit.acVoltageGroup.acVoltage_0.isPhaseEditableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.rlcScreen.model.circuit.acVoltageGroup.acVoltage_0.isPhaseEditableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:528:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:527:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/joist/js/Sim.js:796:25)
id: Bayes Chrome
Snapshot from 2/3/2022, 6:18:37 PM

----------------------------------

circuit-construction-kit-ac : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643937517178%22%2C%22timestamp%22%3A1643964269279%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.rlcScreen.model.circuit.acVoltageGroup.acVoltage_0.isPhaseEditableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.rlcScreen.model.circuit.acVoltageGroup.acVoltage_0.isPhaseEditableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:528:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:527:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/joist/js/Sim.js:796:25)
id: Bayes Chrome
Snapshot from 2/3/2022, 6:18:37 PM

----------------------------------

circuit-construction-kit-ac : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/phet-io-wrappers/input-record-and-playback/?sim=circuit-construction-kit-ac&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643937517178%22%2C%22timestamp%22%3A1643941094774%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.rlcScreen.model.circuit.capacitorGroup.capacitor_1.isClearableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.rlcScreen.model.circuit.capacitorGroup.capacitor_1.isClearableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:528:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:527:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/joist/js/Sim.js:796:25)
id: Bayes Chrome
Snapshot from 2/3/2022, 6:18:37 PM

----------------------------------

circuit-construction-kit-ac : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/studio/?sim=circuit-construction-kit-ac&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643937517178%22%2C%22timestamp%22%3A1643940411609%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.inductorGroup.inductor_0.isClearableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.model.circuit.inductorGroup.inductor_0.isClearableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:528:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:527:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/joist/js/Sim.js:796:25)
id: Bayes Chrome
Snapshot from 2/3/2022, 6:18:37 PM
```

**Comment by KatieWoe** [comment]
Also in dc:
```
circuit-construction-kit-dc : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643937517178%22%2C%22timestamp%22%3A1643941767941%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDc.introScreen.model.circuit.fuseGroup.fuse_0.isRepairableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDc.introScreen.model.circuit.fuseGroup.fuse_0.isRepairableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:528:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:527:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/joist/js/Sim.js:796:25)
id: Bayes Chrome
Snapshot from 2/3/2022, 6:18:37 PM

----------------------------------

circuit-construction-kit-dc : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643937517178%22%2C%22timestamp%22%3A1643961731695%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDc.introScreen.model.circuit.fuseGroup.fuse_0.isRepairableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDc.introScreen.model.circuit.fuseGroup.fuse_0.isRepairableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:528:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:527:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/joist/js/Sim.js:796:25)
id: Bayes Chrome
Snapshot from 2/3/2022, 6:18:37 PM

----------------------------------

circuit-construction-kit-dc : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/phet-io-wrappers/input-record-and-playback/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643937517178%22%2C%22timestamp%22%3A1643940935229%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDc.introScreen.model.circuit.fuseGroup.fuse_1.isRepairableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDc.introScreen.model.circuit.fuseGroup.fuse_1.isRepairableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:528:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:527:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/joist/js/Sim.js:796:25)
id: Bayes Chrome
Snapshot from 2/3/2022, 6:18:37 PM

----------------------------------

circuit-construction-kit-dc : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/studio/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1643937517178%22%2C%22timestamp%22%3A1643941142550%7D
Uncaught Error: Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDc.introScreen.model.circuit.fuseGroup.fuse_1.isRepairableProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDc.introScreen.model.circuit.fuseGroup.fuse_1.isRepairableProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:528:19
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/tandem/js/PhetioObject.js:527:19
at Array.callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/Timer.js:30:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/axon/js/TinyEmitter.js:82:39)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1643937517178/chipper/dist/js/joist/js/Sim.js:796:25)
id: Bayes Chrome
Snapshot from 2/3/2022, 6:18:37 PM
```

**Comment by samreid** [comment]
I pushed a fix for one aspect on CT at the moment, will reopen this or a new issue if it recurs.
