### ISSUE TITLE
CT getLocalToGlobalMatrix unable to work for DAG

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#873]
```
circuit-construction-kit-dc : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647707554210%22%2C%22timestamp%22%3A1647719062556%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/assert/js/assert.js:25:13)
at HBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5728:17)
at HBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5833:36)
at TrashButton.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5873:50)
at TrashButton.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5913:17)
at TrashButton.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5921:17)
at AnimatedPanZoomListener.keepNodeInView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:860:72)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:144:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/19/2022, 10:32:34 AM

----------------------------------

circuit-construction-kit-dc : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647707554210%22%2C%22timestamp%22%3A1647730391242%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading 'isDragged')
TypeError: Cannot read properties of null (reading 'isDragged')
at Circuit.cutVertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/circuit-construction-kit-common/js/model/Circuit.js:546:16)
at VertexNode.keydownListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/circuit-construction-kit-common/js/view/VertexNode.js:249:46)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:1740:23)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:1775:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:1698:10)
at Input.dispatchPDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:1040:12)
at Input.keydownAction.PhetioAction.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:696:14)
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/tandem/js/PhetioAction.js:90:17)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:746:32)
at KeyboardFuzzer.triggerDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/accessibility/KeyboardFuzzer.js:200:13)
id: Bayes Chrome
Snapshot from 3/19/2022, 10:32:34 AM

----------------------------------

circuit-construction-kit-dc : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647707554210%22%2C%22timestamp%22%3A1647776677210%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading 'isDragged')
TypeError: Cannot read properties of null (reading 'isDragged')
at Circuit.cutVertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/circuit-construction-kit-common/js/model/Circuit.js:546:16)
at VertexNode.keydownListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/circuit-construction-kit-common/js/view/VertexNode.js:249:46)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:1740:23)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:1775:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:1698:10)
at Input.dispatchPDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:1040:12)
at Input.keydownAction.PhetioAction.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:696:14)
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/tandem/js/PhetioAction.js:90:17)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/input/Input.js:746:32)
at KeyboardFuzzer.triggerDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/accessibility/KeyboardFuzzer.js:200:13)
id: Bayes Chrome
Snapshot from 3/19/2022, 10:32:34 AM

----------------------------------

circuit-construction-kit-dc : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647707554210%22%2C%22timestamp%22%3A1647800942603%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/assert/js/assert.js:25:13)
at HBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5728:17)
at HBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5833:36)
at TrashButton.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5873:50)
at TrashButton.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5913:17)
at TrashButton.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5921:17)
at AnimatedPanZoomListener.keepNodeInView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:860:72)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:144:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/19/2022, 10:32:34 AM

----------------------------------

circuit-construction-kit-dc : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647707554210%22%2C%22timestamp%22%3A1647838945931%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/assert/js/assert.js:25:13)
at HBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5728:17)
at HBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5833:36)
at TrashButton.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5873:50)
at TrashButton.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5913:17)
at TrashButton.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5921:17)
at AnimatedPanZoomListener.keepNodeInView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:860:72)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:144:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/19/2022, 10:32:34 AM

----------------------------------

circuit-construction-kit-dc : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647707554210%22%2C%22timestamp%22%3A1647857028910%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/assert/js/assert.js:25:13)
at HBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5728:17)
at HBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5833:36)
at TrashButton.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5873:50)
at TrashButton.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5913:17)
at TrashButton.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:5921:17)
at AnimatedPanZoomListener.keepNodeInView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:860:72)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:144:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/19/2022, 10:32:34 AM

----------------------------------

circuit-construction-kit-dc : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/studio/?sim=circuit-construction-kit-dc&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647707554210%22%2C%22timestamp%22%3A1647842656952%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitNode.lightBulbNodeGroup.lightBulbNode_1
Error: Assertion failed: phetioID already registered: circuitConstructionKitDc.labScreen.view.circuitNode.lightBulbNodeGroup.lightBulbNode_1
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/assert/js/assert.js:25:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/phet-io/js/phetioEngine.js:631:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/phet-io/js/phetioEngine.js:1122:20)
at DynamicTandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/tandem/js/Tandem.js:156:36)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/tandem/js/PhetioObject.js:242:17)
at CCKCLightBulbNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:6065:11)
at CCKCLightBulbNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:6044:10)
at new Node (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/scenery/js/nodes/Node.js:500:12)
at new CircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/circuit-construction-kit-common/js/view/CircuitElementNode.js:41:5)
at new FixedCircuitElementNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647707554210/chipper/dist/js/circuit-construction-kit-common/js/view/FixedCircuitElementNode.js:57:5)
id: Bayes Chrome
Snapshot from 3/19/2022, 10:32:34 AM
```

**Comment by jessegreenberg** [comment]
I see this is in the common repo, great. Assigning to myself from https://github.com/phetsims/circuit-construction-kit-ac-virtual-lab/issues/5

**Comment by jessegreenberg** [comment]
From https://github.com/phetsims/circuit-construction-kit-ac-virtual-lab/issues/5#issuecomment-1072780797

> This is happening because the ?fuzzBoard implementation randomly scans the DOM for something to focus. Tab navigation is disabled in this sim so my understanding is that this would not appear in the wild but it would still be good to investigate why it is happening.

**Comment by jessegreenberg** [comment]
This was fixed in the above commit, `panToNode` was replaced with a new `panToTrail` so that this feature works with DAG. `?fuzzBoard` tests are passing locally, closing.
