### ISSUE TITLE
CT cannot read properties of null reading isDragged

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#874]
```
circuit-construction-kit-dc-virtual-lab : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648329557691%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading 'isDragged')
TypeError: Cannot read properties of null (reading 'isDragged')
at Circuit.cutVertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/circuit-construction-kit-common/js/model/Circuit.js:546:16)
at VertexNode.keydownListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/circuit-construction-kit-common/js/view/VertexNode.js:249:46)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:1740:23)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:1775:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:1698:10)
at Input.dispatchPDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:1040:12)
at Input.keydownAction.PhetioAction.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:696:14)
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/tandem/js/PhetioAction.js:90:17)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:746:32)
at KeyboardFuzzer.triggerDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/accessibility/KeyboardFuzzer.js:200:13)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648348291651%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/assert/js/assert.js:25:13)
at HBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5728:17)
at HBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5833:36)
at TrashButton.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5873:50)
at TrashButton.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5913:17)
at TrashButton.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5921:17)
at AnimatedPanZoomListener.keepNodeInView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:860:72)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:144:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648368393216%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading 'isDragged')
TypeError: Cannot read properties of null (reading 'isDragged')
at Circuit.cutVertex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/circuit-construction-kit-common/js/model/Circuit.js:546:16)
at VertexNode.keydownListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/circuit-construction-kit-common/js/view/VertexNode.js:249:46)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:1740:23)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:1775:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:1698:10)
at Input.dispatchPDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:1040:12)
at Input.keydownAction.PhetioAction.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:696:14)
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/tandem/js/PhetioAction.js:90:17)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/input/Input.js:746:32)
at KeyboardFuzzer.triggerDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/accessibility/KeyboardFuzzer.js:200:13)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648389155482%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/assert/js/assert.js:25:13)
at HBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5728:17)
at HBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5833:36)
at TrashButton.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5873:50)
at TrashButton.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5913:17)
at TrashButton.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5921:17)
at AnimatedPanZoomListener.keepNodeInView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:860:72)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:144:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648409272485%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/assert/js/assert.js:25:13)
at HBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5728:17)
at HBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5833:36)
at TrashButton.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5873:50)
at TrashButton.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5913:17)
at TrashButton.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5921:17)
at AnimatedPanZoomListener.keepNodeInView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:860:72)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:144:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648452544419%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/assert/js/assert.js:25:13)
at HBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5728:17)
at HBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5833:36)
at TrashButton.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5873:50)
at TrashButton.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5913:17)
at TrashButton.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5921:17)
at AnimatedPanZoomListener.keepNodeInView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:860:72)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:144:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM

----------------------------------

circuit-construction-kit-dc-virtual-lab : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648470424643%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/assert/js/assert.js:25:13)
at HBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5728:17)
at HBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5833:36)
at TrashButton.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5873:50)
at TrashButton.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5913:17)
at TrashButton.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/nodes/Node.js:5921:17)
at AnimatedPanZoomListener.keepNodeInView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:860:72)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:144:14)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM
```

**Comment by jessegreenberg** [comment]
I took a look because it looked like an alt input problem but I am not sure yet. It seems like `getSelectedVertex` is returning `null` here https://github.com/phetsims/circuit-construction-kit-common/blob/5d939da4ea4887d8190753529b35d78139fb28aa/js/view/VertexNode.ts#L302-L311

But I wasn't able to reproduce it myself with the query params shown in the issue ticket
```brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000```

Let me know if I should look further!

**Comment by samreid** [comment]
This problem hasn't appeared on CT for a while, closing.
