### ISSUE TITLE
phetioID missing from the baseline that was not an archetype: 

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#891]
```
circuit-construction-kit-dc : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661601756989/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661601756989%22%2C%22timestamp%22%3A1661605898680%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.meterNodes.ammeterNode1.probeTextNode.readoutText.textProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.meterNodes.ammeterNode1.probeTextNode.readoutText.textProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661601756989/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:161:18)
at validateOverridesFile (phetioAPIValidation.ts:86:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:912:14)
id: Bayes Puppeteer
Snapshot from 8/27/2022, 6:02:36 AM

```

**Comment by samreid** [comment]
Fixed, closing.

**Comment by KatieWoe** [comment]
I'm seeing this again now that CT is working again.
```
circuit-construction-kit-dc : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662721214770%22%2C%22timestamp%22%3A1662729375517%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 5:00:14 AM

----------------------------------

circuit-construction-kit-dc : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662721214770%22%2C%22timestamp%22%3A1662735950182%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 5:00:14 AM

----------------------------------

circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662721214770%22%2C%22timestamp%22%3A1662730106106%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 5:00:14 AM

----------------------------------

circuit-construction-kit-dc : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/phet-io-wrappers/state/?sim=circuit-construction-kit-dc&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662721214770%22%2C%22timestamp%22%3A1662735152757%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 5:00:14 AM

----------------------------------

circuit-construction-kit-dc : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/studio/?sim=circuit-construction-kit-dc&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662721214770%22%2C%22timestamp%22%3A1662728841647%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty: 3. Any schema entries in the overrides file must exist in the baseline file.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:222:16)
at assertAPIError (phetioAPIValidation.ts:167:15)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 5:00:14 AM

----------------------------------

circuit-construction-kit-dc : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/studio/?sim=circuit-construction-kit-dc&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662721214770%22%2C%22timestamp%22%3A1662735558359%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty: 3. Any schema entries in the overrides file must exist in the baseline file.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:222:16)
at assertAPIError (phetioAPIValidation.ts:167:15)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 5:00:14 AM

----------------------------------

circuit-construction-kit-dc : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/phet-io-wrappers/phet-io-wrappers-tests.html?sim=circuit-construction-kit-dc&phetioDebug=true&phetioWrapperDebug=true
32 out of 33 tests passed. 1 failed.
SimTests: circuit-construction-kit-dc: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/tandem/js/phetioAPIValidation.js:135:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/tandem/js/phetioAPIValidation.js:60:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/phet-io/js/phetioEngine.js:318:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/axon/js/ReadOnlyProperty.js:228:23)
at Property.unguardedSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/axon/js/ReadOnlyProperty.js:178:14)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/axon/js/ReadOnlyProperty.js:161:12)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/axon/js/Property.js:52:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/joist/js/Sim.js:697:56

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visiblePropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 5:00:14 AM

----------------------------------

circuit-construction-kit-dc : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/phet-io-wrappers/phet-io-wrappers-tests.html?sim=circuit-construction-kit-dc
30 out of 31 tests passed. 1 failed.
SimTests: circuit-construction-kit-dc: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/tandem/js/phetioAPIValidation.js:135:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/tandem/js/phetioAPIValidation.js:60:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/phet-io/js/phetioEngine.js:318:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/axon/js/ReadOnlyProperty.js:228:23)
at Property.unguardedSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/axon/js/ReadOnlyProperty.js:178:14)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/axon/js/ReadOnlyProperty.js:161:12)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/axon/js/Property.js:52:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/chipper/dist/js/joist/js/Sim.js:697:56

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visiblePropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: circuitConstructionKitDc.introScreen.view.circuitElementEditContainerNode.tapInstructionTextNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662721214770/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 5:00:14 AM
```

**Comment by samreid** [comment]
Fixed and pushed, thanks for reporting it.  Closing.
