### ISSUE TITLE
CT All descendants must be disposed by the next frame: 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#892]
In several CCK repos:
```
circuit-construction-kit-dc : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663261624168%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDc.labScreen.view.circuitLayerNode.seriesAmmeterNodeGroup.seriesAmmeterNode_0.probeTextNode.readoutText
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDc.labScreen.view.circuitLayerNode.seriesAmmeterNodeGroup.seriesAmmeterNode_0.probeTextNode.readoutText
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:676:18)
at Array.forEach
at forEach (PhetioObject.ts:675:18)
at listener (Timer.ts:33:10)
at (TinyEmitter.ts:109:42)
at emit (Sim.ts:980:24)
id: Bayes Puppeteer
Snapshot from 9/15/2022, 9:05:26 AM
```

**Comment by samreid** [comment]
Fixed, closing.
