### ISSUE TITLE
CT Various

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#897]
Number of CT issues in the different CCK sims
```
circuit-construction-kit-ac-virtual-lab : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668689632376/circuit-construction-kit-ac-virtual-lab/circuit-construction-kit-ac-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac-virtual-lab%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1668689632376%22%2C%22timestamp%22%3A1668700352270%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Cannot add the same listener twice
Error: Assertion failed: Cannot add the same listener twice
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668689632376/assert/js/assert.js:28:13)
at assert (TinyEmitter.ts:121:14)
at addListener (ReadOnlyProperty.ts:406:22)
at link (PressListener.ts:388:78)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (createObservableArray.ts:334:36)
at push (PressListener.ts:800:22)
at inputEvent (Input.ts:1896:93)
at dispatchToListeners (Input.ts:1934:11)
id: Bayes Puppeteer
Snapshot from 11/17/2022, 5:53:52 AM
```
```
circuit-construction-kit-ac : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668689632376/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-ac%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1668689632376%22%2C%22timestamp%22%3A1668692867072%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.view.circuitLayerNode.seriesAmmeterNodeGroup.seriesAmmeterNode_1.readoutText.stringProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitAc.labScreen.view.circuitLayerNode.seriesAmmeterNodeGroup.seriesAmmeterNode_1.readoutText.stringProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668689632376/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:662:18)
at Array.forEach
at forEach (PhetioObject.ts:661:18)
at listener (Timer.ts:33:10)
at (TinyEmitter.ts:109:42)
at emit (Sim.ts:996:24)
id: Bayes Puppeteer
Snapshot from 11/17/2022, 5:53:52 AM
```
```
circuit-construction-kit-dc-virtual-lab : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668689632376/circuit-construction-kit-dc-virtual-lab/circuit-construction-kit-dc-virtual-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc-virtual-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1668689632376%22%2C%22timestamp%22%3A1668694065043%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDcVirtualLab.labScreen.view.circuitLayerNode.seriesAmmeterNodeGroup.seriesAmmeterNode_0.readoutText.stringProperty
Error: Assertion failed: All descendants must be disposed by the next frame: circuitConstructionKitDcVirtualLab.labScreen.view.circuitLayerNode.seriesAmmeterNodeGroup.seriesAmmeterNode_0.readoutText.stringProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668689632376/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:662:18)
at Array.forEach
at forEach (PhetioObject.ts:661:18)
at listener (Timer.ts:33:10)
at (TinyEmitter.ts:109:42)
at emit (Sim.ts:996:24)
id: Bayes Puppeteer
Snapshot from 11/17/2022, 5:53:52 AM
```
```
circuit-construction-kit-dc : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668689632376/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-dc%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1668689632376%22%2C%22timestamp%22%3A1668694917481%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'node')
TypeError: Cannot read properties of undefined (reading 'node')
at node (Instance.js:1425:45)
at listener (TinyEmitter.ts:95:8)
at emit (Node.ts:968:29)
at removeChildWithIndex (Node.ts:908:9)
at removeChild (CircuitLayerNode.ts:330:16)
at (TinyEmitter.ts:109:42)
at emit (Emitter.ts:60:21)
at emit (createObservableArray.ts:359:79)
at Array.forEach
at forEach (createObservableArray.ts:359:20)
id: Bayes Puppeteer
Snapshot from 11/17/2022, 5:53:52 AM
```

**Comment by samreid** [comment]
Looks fixed in the latest column, closing.
